version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.1.3
  aws-ecs: circleci/aws-ecs@3.2

jobs:
  build-and-test:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true

      # Build and test Go service
      - run:
          name: Build Go service
          command: |
            cd crypto-service
            docker build --platform linux/arm64 -t crypto-service:${CIRCLE_SHA1} .

      # Build and test Node.js service
      - run:
          name: Build Node.js service
          command: |
            cd text-processor
            docker build --platform linux/amd64 -t text-processor:${CIRCLE_SHA1} .

  deploy:
    docker:
      - image: cimg/base:2023.03
    steps:
      - aws-ecr/build-and-push-image:
          repo: "${AWS_ECR_REPO_NAME}"
          tag: "crypto-service-${CIRCLE_SHA1}"
          path: ./crypto-service
          platform: linux/arm64

      - aws-ecr/build-and-push-image:
          repo: "${AWS_ECR_REPO_NAME}"
          tag: "text-processor-${CIRCLE_SHA1}"
          path: ./text-processor
          platform: linux/amd64

      # Updated ECS deployment command
      - aws-ecs/deploy_service_update:
          requires:
            - aws-ecr/build_and_push_image
          cluster: "${ECS_CLUSTER_NAME}"
          container-image-name-updates: "container=${CONTAINER_NAME},tag=${CIRCLE_SHA1}"
          family: "${ECS_TASK_FAMILY}"
          service: "${ECS_SERVICE_NAME}"

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-and-test
      - deploy:
          requires:
            - build-and-test
          filters:
            branches:
              only: main
