version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.15.3
  aws-cli: circleci/aws-cli@4.1
  
jobs:
  build-and-test:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true


  deploy:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true

    # Debug AWS configuration
      - run:
          name: Debug AWS Configuration
          command: |
            echo "AWS Region: ${AWS_REGION}"
            echo "AWS Account ID: ${AWS_ACCOUNT_ID}"
            echo "ECR Repository: ${AWS_ECR_REPO_NAME}"


      
      # Login to AWS ECR
      - run:
          name: Login to AWS ECR
          command: |
            aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com

      # Build and push crypto-service
      - run:
          name: Build and push crypto-service
          command: |
            cd nodejs-service
            docker build --platform linux/arm64 -t ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${AWS_ECR_REPO_NAME}:nodejs-service-${CIRCLE_SHA1} .
            docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${AWS_ECR_REPO_NAME}:crypto-service-${CIRCLE_SHA1}

      # Build and push text-processor
      - run:
          name: Build and push text-processor
          command: |
            cd python-service
            docker build --platform linux/amd64 -t ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${AWS_ECR_REPO_NAME}:python-processor-${CIRCLE_SHA1} .
            docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${AWS_ECR_REPO_NAME}:text-processor-${CIRCLE_SHA1}

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-and-test
      - deploy:
          requires:
            - build-and-test
          filters:
            branches:
              only: main
